"""
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def even_fib_sum(bound):
    """

    :param bound:
    :return:
    """
    prev = 2
    next = 8
    total = prev
    while next <= bound:
        total += next
        temp = next
        next = 4*next + prev
        prev = temp
    return total


if __name__ == '__main__':
    print(even_fib_sum(4e6))
